### ISSUE TITLE
Integration for Tortoise GIT not work in "Git view"

### ISSUE THREAD

**Issue by peterprvy** [ContextQuickie/ContextQuickie#30]
1. Swittch eclipse to "GIT view"
2. Use "Sync...", or other command
3. Error : "The parameters '/path' and '/pathfile' are mutually exclusive error"

![2020-08-03_143007](https://user-images.githubusercontent.com/36068077/89182778-903dc780-d596-11ea-864f-fb503a3b7118.png)
![2020-08-03_143007](https://user-images.githubusercontent.com/36068077/89182350-dc3c3c80-d595-11ea-9349-4b3d434a8692.png)

If eclipse in "java view", commnad is OK

**Comment by ContextQuickie** [comment]
Hello @peterprvy ,
I had a look at this topic. It's not that easy to get file/folder information from the Git view because the Git plugin doesn't support the IResource interface.
Onle way I figured out was to use reflection to see if the selected tree node implements getPath() and calling it if available. Doesn't look very nice in the code.
Another solution would be to add egit as a dependency to ContextQuickie to have access to their classes but I want to avoid this dependency, e.g. for users who don't use Tortoise Git.
Maybe I'll find a better solution in the next days.
BR
Roland

**Comment by ContextQuickie** [comment]
Hello @peterprvy ,
I didn't find a good solution for this problem so i disabled the TortoiseGit plugin for the Git Repositories view.
BR
Roland
